/*
 * OpenFileDialog.java
 *
 * Created on December 21, 2007, 2:48 PM
 */

package common;

import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 * 
 * @author Mert
 */
public class OpenFileDialog extends javax.swing.JPanel {


	private static final long serialVersionUID = 1L;

	/** Creates new form OpenFileDialog */
	public OpenFileDialog() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	private void initComponents() {
		jFileChooser1 = new javax.swing.JFileChooser();

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 448,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 289,
				javax.swing.GroupLayout.PREFERRED_SIZE));
	}// </editor-fold>//GEN-END:initComponents

	public JFileChooser getChooser() {
		return this.jFileChooser1;
	}

	public int showChooser(JFrame parent) {
		int returnVal = this.getChooser().showOpenDialog(parent);
		return returnVal;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JFileChooser jFileChooser1;
	// End of variables declaration//GEN-END:variables

}
